### PR TITLE
feat: improve ios installation

### PR DESCRIPTION
**Pull request by niall-shaw**
use podspec dependency to fetch indy

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]
Nice, good improvements!

**Comment by TimoGlastra** [comment]
Now that I think of it this is a breaking change as people that don't have the source defined wont know the indy dependency.  Will need to release this as 0.3.0

**Comment by TimoGlastra** [comment]
Also, is there a way to do custom installation still? Not sure if everyone is happy to rely on a s3 service from Absa

**Comment by JamesKEbert** [comment]
Nice! This is significantly easier IMO

+1 to a 0.3.0 release. 

> Also, is there a way to do custom installation still? Not sure if everyone is happy to rely on a s3 service from Absa

Might be smart if possible to make this an option still

**Comment by JamesKEbert** [comment]
Some small install notes:

- Upon a fresh RN init, the BITCODE is set to `yes` for the project and in the target it is `yes` for release and `no` for debug. This needs to be set `no`. 
- Additionally, if you're _not_ using Swift 5.0 (which has always been the case for me), Build Libraries for Distribution needs to be set to `yes`. By default it is set to `no` in both the project and target.
- Simulators need to be disabled still AFAIK. 

(a note for the aries.js.org docs, we probably should note that Hermes is required)

**Comment by jakubkoci** [comment]
@TimoGlastra 
> Also, is there a way to do custom installation still? Not sure if everyone is happy to rely on a s3 service from Absa

You can create your own Spec file and just replace path to your Spec repo here:
```
source 'https://github.com/AbsaOSS/dlt-cocoapods-specs.git'
```

**Comment by jakubkoci** [comment]
@JamesKEbert 

> (a note for the aries.js.org docs, we probably should note that Hermes is required)

This scares me because we don't run Hermes 😱  What do you mean by that? Why is it required? 🤔

**Comment by JamesKEbert** [comment]
> This scares me because we don't run Hermes 😱 What do you mean by that? Why is it required? 🤔

@jakubkoci as per our findings https://github.com/hyperledger/indy-sdk/issues/2346#issuecomment-841000640 we've found that in order to run indy-sdk on Android successfully on a React Native version higher than 0.61.5 you must have Hermes enabled (or more specifically be able to perform any ledger operations using indy-sdk). This doesn't apply to iOS, but we've also used it there so that we're consistent between the two platforms. 

It's possible newer versions of RN have addressed this (especially given the TurboModules changes), however I mostly doubt it unfortunately.

**Comment by JamesKEbert** [comment]
> Also, is there a way to do custom installation still? Not sure if everyone is happy to rely on a s3 service from Absa
> 
> You can create your own Spec file and just replace path to your Spec repo here:
> 
> source 'https://github.com/AbsaOSS/dlt-cocoapods-specs.git'

Is it worth placing/managing this in a Hyperledger repo?

**Comment by JamesKEbert** [comment]
@TimoGlastra, would you like me to make a PR to update the install instructions to include the Bitcode, etc?

**Pull request merged**
