### PR TITLE
Feature/revocation

### PR DESCRIPTION
**Pull request by JamesKEbert**
Adds recipient revocation capabilities for both Android and iOS:
    buildGetRevocRegDefRequest
    parseGetRevocRegDefResponse
    buildGetRevocRegDeltaRequest
    parseGetRevocRegDeltaResponse
    createRevocationState
This is a followup to #15. @TheTreek contributed the Android portions.
This fixes the types of the previous PR and readjusted the method positioning to align with Indy.

All commits should be signed. If there's still issues the repo may be checking for GCP signed keys, not DCO signoff.

### CODE REVIEW

**Review by TimoGlastra — COMMENTED** [review]
LGTM. Great work @TheTreek and @JamesKEbert :)

**Review by TimoGlastra — APPROVED** [review]

**Comment by TimoGlastra** [comment]
It seems like all commits need to be signed, which is different from signing-off commits

https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/about-commit-signature-verification

**Comment by TimoGlastra** [comment]
I've disabled the requirement for signing, we can now merge if ready

**Comment by jakubkoci** [comment]
Thanks, @JamesKEbert I merged the #15 and there are some conflicts here. I'm sorry for the inconvenience and if I misunderstood what to merge first 🤷‍♂️

**Comment by JamesKEbert** [comment]
No worries, not hard to fix, fortunately! :)

**Comment by TimoGlastra** [comment]
This is now released in version [0.1.14](https://github.com/hyperledger/indy-sdk-react-native/releases/tag/0.1.14)

**Pull request merged**
